### ISSUE TITLE
请问：客户端不能发图片？

### ISSUE THREAD

**Issue by WuHuaJi0** [lincanbin/Android-Carbon-Forum#10]
自己编译了一个客户端，发现回复发帖都只有一个文本输入框，没发现可以发图片的地方

**Comment by lincanbin** [comment]
对啊。还没做。
这段时间我又有一些比较重要的事要处理了，比较忙，过段时间闲了会加上。
毕竟我也是一个要工作赚钱养自己的软件工程师，不是无业游民，麻烦谅解下。

有兴趣的可以自己做，上传图片的接口已经有了，可以参考PC端接口。

**Comment by WuHuaJi0** [comment]
en  理解理解 :）
