### ISSUE TITLE
No Network issue

### ISSUE THREAD

**Issue by harry-saputra** [lincanbin/Android-Carbon-Forum#4]
hi lincanbin,

try running this apps on real device via usb debugging, and got this error :

02-11 10:21:13.210 3893-4704/com.forum.syareaworld D/POST URL :: http://128.199.105.130:2018/page/1
02-11 10:21:13.210 3893-4704/com.forum.syareaworld D/POST parameter: SKey=1503&STime=1455160873&SValue=a459e3c54f35c65920ef3f81acdd2e01
02-11 10:21:44.520 3893-4704/com.forum.syareaworld D/Post Error: No Network
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err: java.net.ProtocolException: content-length promised 66 bytes, but received 0
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at com.android.okhttp.internal.http.RetryableOutputStream.close(RetryableOutputStream.java:52)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:636)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at com.forum.syareaworld.util.HttpUtil.postRequest(HttpUtil.java:192)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at com.forum.syareaworld.IndexActivity$GetTopicsTask.doInBackground(IndexActivity.java:435)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at com.forum.syareaworld.IndexActivity$GetTopicsTask.doInBackground(IndexActivity.java:373)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-11 10:21:44.520 3893-4704/com.forum.syareaworld W/System.err:     at java.lang.Thread.run(Thread.java:841)

any clue ? thanks!

**Comment by harry-saputra** [comment]
i am using nginx on web server

**Comment by lincanbin** [comment]
You must first set API Domainname. 

![qq 20160211172920](https://cloud.githubusercontent.com/assets/5785188/12973060/05a6df36-d0e5-11e5-9c82-740bf60b3e20.png)

**Comment by harry-saputra** [comment]
can i use only ip address ? http://128.199.105.130:2018

just modified it but no luck. thanks for the respond

**Comment by lincanbin** [comment]
Domainname API can not be the same as the PC domainname.

**Comment by lincanbin** [comment]
Maybe you can modify the `hosts` file in your system to test

**Comment by lincanbin** [comment]
Modify your nginx.conf like this:

```
server {
    listen       2018;
    listen       2019;
    listen       2020;
    server_name  128.199.105.130;
    ……
}
```

And then: 
![qq 20160211202442](https://cloud.githubusercontent.com/assets/5785188/12976234/8435462c-d0fd-11e5-8578-7c9b0ce5c66f.png)

**Comment by harry-saputra** [comment]
done, but still no luck

![selection_012](https://cloud.githubusercontent.com/assets/6844866/12976834/63fd6906-d0f9-11e5-9b5f-8dc9da2e42a7.png)
![selection_011](https://cloud.githubusercontent.com/assets/6844866/12976835/642ae070-d0f9-11e5-877c-7bfc1fa8ad60.png)

**Comment by harry-saputra** [comment]
it works now, my bad having wrong character on nginx.conf. big thanks @lincanbin !

**Comment by lincanbin** [comment]
You're welcome.
